apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.0.0.50-10.0.0.90
    - name: production-pool
      protocol: layer2
      addresses:
      - 10.0.0.110-10.0.0.150