apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: aruns1975/springbootapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  annotations:
    metallb.universe.tf/address-pool: production-pool
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: myapp
  type: LoadBalancer