Vagrant.configure("2") do |config|

  #
  # Environment Variables
  #
  SCRIPT_FOLDER  = "../scripts"
  IMAGE_NAME     = "aruns1975/ubuntuk8s"
  IMAGE_VERSION  = "5.0"
  WORKER_COUNT   = 1

  MASTER_NODE_PREFIX = "master-node-"
  MASTER_NODE_IP = "10.0.0.100"

  WORKER_NODE_PREFIX = "worker-node-"
  WORKER_NODE_IP_PREFIX = "10.0.0.10"
  #
  # Creations of host entries on all the nodes
  #
  config.vm.provision "shell", path: "#{SCRIPT_FOLDER}/create_user.sh"
  config.vm.provision "shell", inline: <<-SHELL
      echo "10.0.0.100  master-node-1" >> /etc/hosts
      echo "10.0.0.101  worker-node-1" >> /etc/hosts
      echo "10.0.0.102  worker-node-2" >> /etc/hosts
  SHELL
 
  #
  # Master node configuration
  #
  config.vm.define "#{MASTER_NODE_PREFIX}1" do |master|
    master.vm.box = IMAGE_NAME
    master.vm.box_version = IMAGE_VERSION
    master.vm.hostname = "#{MASTER_NODE_PREFIX}1"
    master.vm.network "private_network", ip: MASTER_NODE_IP
    master.vm.provider "virtualbox" do |vb|
        vb.memory = 4048
        vb.cpus = 2
    vb.name="#{MASTER_NODE_PREFIX}1"
    end
    master.vm.provision "shell", path: "#{SCRIPT_FOLDER}/master/install_kube_server.sh"
    master.vm.provision "shell", path: "#{SCRIPT_FOLDER}/master/install_calico.sh"
    master.vm.provision "shell", path: "#{SCRIPT_FOLDER}/master/install_dashboard.sh"
    master.vm.provision "shell", path: "#{SCRIPT_FOLDER}/master/install_metric.sh"
    master.vm.provision "shell", path: "#{SCRIPT_FOLDER}/master/install_metal_lb.sh"
    #master.vm.provision "shell", path: "#{SCRIPT_FOLDER}/master/install_helm.sh"
    #master.vm.provision "shell", path: "#{SCRIPT_FOLDER}/master/install_contour.sh"
    #master.vm.provision "shell", path: "#{SCRIPT_FOLDER}/master/install_istio.sh"
    #master.vm.provision "shell", path: "#{SCRIPT_FOLDER}/master/install_promethus.sh"
    # master.vm.provision "shell", path: "#{SCRIPT_FOLDER}/install_helm.sh"
  end
  #
  # Worker node vagrant configuration
  #
  (1..WORKER_COUNT).each do |i|
    config.vm.define "#{WORKER_NODE_PREFIX}#{i}" do |node|
      node.vm.box = IMAGE_NAME
      node.vm.box_version = IMAGE_VERSION
      node.vm.hostname = "#{WORKER_NODE_PREFIX}#{i}"
      node.vm.network "private_network", ip: "#{WORKER_NODE_IP_PREFIX}#{i}"
      node.vm.provider "virtualbox" do |vb|
          vb.memory = 2048
          vb.cpus = 1
      vb.name="#{WORKER_NODE_PREFIX}#{i}"
      end
      node.vm.provision "shell", path: "#{SCRIPT_FOLDER}/worker/install_worker.sh"
    end 
  end
end