Vagrant.configure("2") do |config|

  #
  # Environment Variables
  #
  SCRIPT_FOLDER  = "./scripts"
  NODE_IP        = "10.0.0.200"
  IMAGE_NAME     = "aruns1975/dockercentos"
  IMAGE_VERSION  = "1.0"
  NODE_NAME      = "docker-node"
  #
  # Creations of host entries on all the nodes
  #
  config.vm.provision "shell", path: "#{SCRIPT_FOLDER}/create_root_user.sh"
  #config.vm.provision "shell", inline: <<-SHELL
  #    apt-get update -y
  #    echo "10.0.0.100  master-node-1" >> /etc/hosts
  #    echo "10.0.0.101  worker-node-1" >> /etc/hosts
  #    echo "10.0.0.102  worker-node-2" >> /etc/hosts
  #SHELL
 
  #
  # Master node configuration
  #
  config.vm.define "#{NODE_NAME}" do |master|
    master.vm.box = IMAGE_NAME
    master.vm.box_version = IMAGE_VERSION
    master.vm.hostname = "#{NODE_NAME}"
    master.vm.network "private_network", ip: NODE_IP
    master.vm.provider "virtualbox" do |vb|
        vb.memory = 2024
        vb.cpus = 2
    vb.name="#{NODE_NAME}"
    end
    master.vm.provision "shell", path: "#{SCRIPT_FOLDER}/install_docker_compose.sh"
  end
end