apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: nginx-pod
spec:
  containers:
  - name: mycontainer
    image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: my-np-service
spec:
  type: NodePort
  selector:
    app: nginx-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: my-lb-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
      