apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-rest-app
  labels:
    appName: my-test-app
    app-tier: service-tier
    type: Deployment
spec:
  selector:
    matchLabels:
      appName: my-test-app
      app-tier: service-tier
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      name: rest-tier-pod
      labels:
        appName: my-test-app
        app-tier: service-tier
        type: replicas
    spec:
      containers:
      - name: rest-tier-container
        image: aruns1975/my-first-java-web-app:2.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: rest-tier-nodeport-service
  labels:
    appName: my-test-app
    app-tier: service-tier
    type: service
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30003
    targetPort: 8080
    protocol: TCP
  selector:
    appName: my-test-app
    app-tier: service-tier
---
apiVersion: v1
kind: Service
metadata:
  name: rest-tier-lb-service
  labels:
    appName: my-test-app
    app-tier: service-tier
    type: service
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    appName: my-test-app
    app-tier: service-tier
  type: LoadBalancer