Vagrant.configure("2") do |config|
    VAGRANT_IMAGE_NAME = "ubuntu/focal64"
    VAGRANT_IMAGE_VERSION = "20210624.0.0"
    SCRIPT_FOLDER = "../scripts"    

    config.vm.define "master-node" do |master|
      master.vm.box = VAGRANT_IMAGE_NAME
      master.vm.box_version = VAGRANT_IMAGE_VERSION
      master.vm.hostname = "master-node"
      master.vm.network "private_network", ip: "10.0.0.10"
      master.vm.provider "virtualbox" do |vb|
          vb.memory = 4048
          vb.cpus = 2
		  vb.name="master-node"
      end
      master.vm.provision "shell", path: "#{SCRIPT_FOLDER}/kubernetes_image/install_kubeadm_1_23_3.sh"
      master.vm.provision "shell", path: "#{SCRIPT_FOLDER}/kubernetes_image/install_helm.sh"
    end
  end